#services:
#  mongo:
#    image: mongo:latest
#    container_name: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db
#
#  studentmanagement:
#    build: .
#    container_name: studentmanagement
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongo
#
#volumes:
#  mongo-data:

version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/studentdb
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongo:27017/studentdb
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mongodb_data:

